In [2]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn import metrics

In [3]:
cancer_data = datasets.load_breast_cancer()

In [4]:
cancer_data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [6]:
cancer_data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
X_train,X_test,Y_train,Y_test = train_test_split(cancer_data.data,cancer_data.target,test_size=0.5,random_state=42)

In [8]:
cls = SVC(kernel='linear')

In [10]:
cls.fit(X_train,Y_train)

SVC(kernel='linear')

In [12]:
y_pred = cls.predict(X_test)

In [13]:
y_pred

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1])

In [14]:
from sklearn.metrics import accuracy_score

In [15]:
accuracy_score(Y_test,y_pred)

0.9649122807017544

In [18]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [19]:
recall_score(Y_test,y_pred)

0.9732620320855615

In [21]:
precision_score(Y_test,y_pred)

0.9732620320855615

In [23]:
f1_score(Y_test,y_pred)

0.9732620320855615

In [24]:
from sklearn.model_selection import cross_val_score

In [27]:
cross_val_score(cls,X_train,Y_train,cv=10)

array([0.93103448, 0.96551724, 0.96551724, 0.96551724, 1.        ,
       1.        , 0.96428571, 0.92857143, 0.89285714, 0.89285714])

In [28]:
from sklearn.metrics import classification_report

In [30]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.95      0.95        98
           1       0.97      0.97      0.97       187

    accuracy                           0.96       285
   macro avg       0.96      0.96      0.96       285
weighted avg       0.96      0.96      0.96       285



In [31]:
from sklearn.metrics import confusion_matrix

In [32]:
confusion_matrix(Y_test,y_pred)

array([[ 93,   5],
       [  5, 182]], dtype=int64)

# Support vector Machine-2

In [35]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [37]:
df = pd.read_csv(r"C:\Users\USER\Downloads\voice.csv.zip")

In [39]:
df.sample(4)

meanfreq        sd    median       Q25       Q75       IQR      skew  \
1636  0.184438  0.057147  0.190088  0.171408  0.213284  0.041877  3.048678   
1531  0.135390  0.079694  0.116456  0.100607  0.213847  0.113240  8.887654   
3099  0.162709  0.055139  0.169410  0.161988  0.181657  0.019669  5.687925   
1001  0.204944  0.058953  0.219478  0.160348  0.253565  0.093217  1.263550   

            kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
1636   13.728153  0.898208  0.457623  ...  0.184438  0.174592  0.015764   
1531  152.919703  0.898122  0.462075  ...  0.135390  0.101600  0.015936   
3099   41.793729  0.866102  0.435705  ...  0.162709  0.144035  0.025000   
1001    4.020002  0.912255  0.324354  ...  0.204944  0.117905  0.046921   

        maxfun   meandom    mindom     maxdom    dfrange   modindx   label  
1636  0.275862  0.299862  0.007812   5.101562   5.093750  0.073273  female  
1531  0.258065  0.030331  0.007812   0.125000   0.117188  0.395960    male  
3099  0.192308  0.759090  0.166016   3.964844   3.798828  0.321594  female  
1001  0.272727  1.222592  0.023438  10.968750  10.945312  0.073174    male  

[4 rows x 21 columns]

In [40]:
df.head()

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0  0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1  0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2  0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3  0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4  0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   

          kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0   274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1   634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2  1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3     4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4     4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   

     maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0  0.275862  0.007812  0.007812  0.007812  0.000000  0.000000   male  
1  0.250000  0.009014  0.007812  0.054688  0.046875  0.052632   male  
2  0.271186  0.007990  0.007812  0.015625  0.007812  0.046512   male  
3  0.250000  0.201497  0.007812  0.562500  0.554688  0.247119   male  
4  0.266667  0.712812  0.007812  5.484375  5.476562  0.208274   male  

[5 rows x 21 columns]

In [41]:
df.isnull().sum()

meanfreq    0
sd          0
median      0
Q25         0
Q75         0
IQR         0
skew        0
kurt        0
sp.ent      0
sfm         0
mode        0
centroid    0
meanfun     0
minfun      0
maxfun      0
meandom     0
mindom      0
maxdom      0
dfrange     0
modindx     0
label       0
dtype: int64

In [42]:
df.corr()

meanfreq        sd    median       Q25       Q75       IQR  \
meanfreq  1.000000 -0.739039  0.925445  0.911416  0.740997 -0.627605   
sd       -0.739039  1.000000 -0.562603 -0.846931 -0.161076  0.874660   
median    0.925445 -0.562603  1.000000  0.774922  0.731849 -0.477352   
Q25       0.911416 -0.846931  0.774922  1.000000  0.477140 -0.874189   
Q75       0.740997 -0.161076  0.731849  0.477140  1.000000  0.009636   
IQR      -0.627605  0.874660 -0.477352 -0.874189  0.009636  1.000000   
skew     -0.322327  0.314597 -0.257407 -0.319475 -0.206339  0.249497   
kurt     -0.316036  0.346241 -0.243382 -0.350182 -0.148881  0.316185   
sp.ent   -0.601203  0.716620 -0.502005 -0.648126 -0.174905  0.640813   
sfm      -0.784332  0.838086 -0.661690 -0.766875 -0.378198  0.663601   
mode      0.687715 -0.529150  0.677433  0.591277  0.486857 -0.403764   
centroid  1.000000 -0.739039  0.925445  0.911416  0.740997 -0.627605   
meanfun   0.460844 -0.466281  0.414909  0.545035  0.155091 -0.534462   
minfun    0.383937 -0.345609  0.337602  0.320994  0.258002 -0.222680   
maxfun    0.274004 -0.129662  0.251328  0.199841  0.285584 -0.069588   
meandom   0.536666 -0.482726  0.455943  0.467403  0.359181 -0.333362   
mindom    0.229261 -0.357667  0.191169  0.302255 -0.023750 -0.357037   
maxdom    0.519528 -0.482278  0.438919  0.459683  0.335114 -0.337877   
dfrange   0.515570 -0.475999  0.435621  0.454394  0.335648 -0.331563   
modindx  -0.216979  0.122660 -0.213298 -0.141377 -0.216475  0.041252   

              skew      kurt    sp.ent       sfm      mode  centroid  \
meanfreq -0.322327 -0.316036 -0.601203 -0.784332  0.687715  1.000000   
sd        0.314597  0.346241  0.716620  0.838086 -0.529150 -0.739039   
median   -0.257407 -0.243382 -0.502005 -0.661690  0.677433  0.925445   
Q25      -0.319475 -0.350182 -0.648126 -0.766875  0.591277  0.911416   
Q75      -0.206339 -0.148881 -0.174905 -0.378198  0.486857  0.740997   
IQR       0.249497  0.316185  0.640813  0.663601 -0.403764 -0.627605   
skew      1.000000  0.977020 -0.195459  0.079694 -0.434859 -0.322327   
kurt      0.977020  1.000000 -0.127644  0.109884 -0.406722 -0.316036   
sp.ent   -0.195459 -0.127644  1.000000  0.866411 -0.325298 -0.601203   
sfm       0.079694  0.109884  0.866411  1.000000 -0.485913 -0.784332   
mode     -0.434859 -0.406722 -0.325298 -0.485913  1.000000  0.687715   
centroid -0.322327 -0.316036 -0.601203 -0.784332  0.687715  1.000000   
meanfun  -0.167668 -0.194560 -0.513194 -0.421066  0.324771  0.460844   
minfun   -0.216954 -0.203201 -0.305826 -0.362100  0.385467  0.383937   
maxfun   -0.080861 -0.045667 -0.120738 -0.192369  0.172329  0.274004   
meandom  -0.336848 -0.303234 -0.293562 -0.428442  0.491479  0.536666   
mindom   -0.061608 -0.103313 -0.294869 -0.289593  0.198150  0.229261   
maxdom   -0.305651 -0.274500 -0.324253 -0.436649  0.477187  0.519528   
dfrange  -0.304640 -0.272729 -0.319054 -0.431580  0.473775  0.515570   
modindx  -0.169325 -0.205539  0.198074  0.211477 -0.182344 -0.216979   

           meanfun    minfun    maxfun   meandom    mindom    maxdom  \
meanfreq  0.460844  0.383937  0.274004  0.536666  0.229261  0.519528   
sd       -0.466281 -0.345609 -0.129662 -0.482726 -0.357667 -0.482278   
median    0.414909  0.337602  0.251328  0.455943  0.191169  0.438919   
Q25       0.545035  0.320994  0.199841  0.467403  0.302255  0.459683   
Q75       0.155091  0.258002  0.285584  0.359181 -0.023750  0.335114   
IQR      -0.534462 -0.222680 -0.069588 -0.333362 -0.357037 -0.337877   
skew     -0.167668 -0.216954 -0.080861 -0.336848 -0.061608 -0.305651   
kurt     -0.194560 -0.203201 -0.045667 -0.303234 -0.103313 -0.274500   
sp.ent   -0.513194 -0.305826 -0.120738 -0.293562 -0.294869 -0.324253   
sfm      -0.421066 -0.362100 -0.192369 -0.428442 -0.289593 -0.436649   
mode      0.324771  0.385467  0.172329  0.491479  0.198150  0.477187   
centroid  0.460844  0.383937  0.274004  0.536666  0.229261  0.519528   
meanfun   1.000000  0.339387  0.311950  0.270840

In [43]:
df.cov()  # covariance

meanfreq        sd    median       Q25       Q75       IQR  \
meanfreq  0.000895 -0.000368  0.001007  0.001327  0.000524 -0.000803   
sd       -0.000368  0.000277 -0.000341 -0.000687 -0.000063  0.000623   
median    0.001007 -0.000341  0.001322  0.001372  0.000629 -0.000743   
Q25       0.001327 -0.000687  0.001372  0.002370  0.000549 -0.001821   
Q75       0.000524 -0.000063  0.000629  0.000549  0.000559  0.000010   
IQR      -0.000803  0.000623 -0.000743 -0.001821  0.000010  0.001830   
skew     -0.040893  0.022215 -0.039689 -0.065949 -0.020684  0.045265   
kurt     -1.275764  0.777957 -1.194037 -2.300099 -0.474872  1.825227   
sp.ent   -0.000809  0.000537 -0.000821 -0.001419 -0.000186  0.001233   
sfm      -0.004166  0.002477 -0.004271 -0.006627 -0.001587  0.005040   
mode      0.001588 -0.000680  0.001902  0.002222  0.000889 -0.001334   
centroid  0.000895 -0.000368  0.001007  0.001327  0.000524 -0.000803   
meanfun   0.000445 -0.000251  0.000487  0.000857  0.000118 -0.000739   
minfun    0.000221 -0.000111  0.000236  0.000300  0.000117 -0.000183   
maxfun    0.000247 -0.000065  0.000275  0.000293  0.000203 -0.000090   
meandom   0.008433 -0.004222  0.008707  0.011950  0.004459 -0.007491   
mindom    0.000434 -0.000377  0.000440  0.000931 -0.000036 -0.000967   
maxdom    0.054730 -0.028278  0.056195  0.078794  0.027894 -0.050900   
dfrange   0.054296 -0.027901  0.055755  0.077862  0.027930 -0.049933   
modindx  -0.000775  0.000244 -0.000926 -0.000822 -0.000611  0.000211   

                skew          kurt    sp.ent       sfm      mode  centroid  \
meanfreq   -0.040893     -1.275764 -0.000809 -0.004166  0.001588  0.000895   
sd          0.022215      0.777957  0.000537  0.002477 -0.000680 -0.000368   
median     -0.039689     -1.194037 -0.000821 -0.004271  0.001902  0.001007   
Q25        -0.065949     -2.300099 -0.001419 -0.006627  0.002222  0.001327   
Q75        -0.020684     -0.474872 -0.000186 -0.001587  0.000889  0.000524   
IQR         0.045265      1.825227  0.001233  0.005040 -0.001334 -0.000803   
skew       17.982084    559.020683 -0.037281  0.059992 -0.142365 -0.040893   
kurt      559.020683  18205.743623 -0.774672  2.632018 -4.236781 -1.275764   
sp.ent     -0.037281     -0.774672  0.002023  0.006918 -0.001130 -0.000809   
sfm         0.059992      2.632018  0.006918  0.031514 -0.006660 -0.004166   
mode       -0.142365     -4.236781 -0.001130 -0.006660  0.005960  0.001588   
centroid   -0.040893     -1.275764 -0.000809 -0.004166  0.001588  0.000895   
meanfun    -0.022968     -0.848046 -0.000746 -0.002415  0.000810  0.000445   
minfun     -0.017682     -0.526967 -0.000264 -0.001235  0.000572  0.000221   
maxfun     -0.010313     -0.185331 -0.000163 -0.001027  0.000400  0.000247   
meandom    -0.750211    -21.488711 -0.006935 -0.039946  0.019928  0.008433   
mindom     -0.016537     -0.882384 -0.000840 -0.003254  0.000968  0.000434   
maxdom     -4.563846   -130.416362 -0.051355 -0.272940  0.129720  0.054730   
dfrange    -4.547309   -129.533978 -0.050516 -0.269686  0.128752  0.054296   
modindx    -0.085771     -3.312846  0.001064  0.004485 -0.001682 -0.000775   

           meanfun    minfun    maxfun    meandom    mindom      maxdom  \
meanfreq  0.000445  0.000221  0.000247   0.008433  0.000434    0.054730   
sd       -0.000251 -0.000111 -0.000065  -0.004222 -0.000377   -0.028278   
median    0.000487  0.000236  0.000275   0.008707  0.000440    0.056195   
Q25       0.000857  0.000300  0.000293   0.011950  0.000931    0.078794   
Q75       0.000118  0.000117  0.000203   0.004459 -0.000036    0.027894   
IQR      -0.000739 -0.000183 -0.000090  -0.007491 -0.000967   -0.050900   
skew     -0.022968 -0.017682 -0.010313  -0.750211 -0.016537   -4.563846   
kurt     -0.848046 -0.526967 -0.185331 -21.488711 -0.882384 -130.416362   
sp.ent   -0.000746 -0.000264 -0.000163  -0.006935 -0.000840   -0.051355   
sfm      -0.002415 -0.001235 -0.001027  -0.039946 -0.003254   -0.272940   
mode      0.000810  0.000572  0.0

In [44]:
df.shape

(3168, 21)

In [49]:
male = df[df['label']=='male']

In [50]:
female = df[df['label']=='female']

In [51]:
male.shape

(1584, 21)

In [53]:
female.shape

(1584, 21)

## separating features and labels

In [54]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [55]:
X

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt    sp.ent       sfm      mode  centroid   meanfun    minfun  \
0      274.402906  0.893369  0.491918  0.000000  0.059781  0.084279  0.015702   
1      634.613855  0.892193  0.513724  0.000000  0.066009  0.107937  0.015826   
2     1024.927705  0.846389  0.478905  0.000000  0.077316  0.098706  0.015656   
3        4.177296  0.963322  0.727232  0.083878  0.151228  0.088965  0.017798   
4        4.333713  0.971955  0.783568  0.104261  0.135120  0.106398  0.016931   
...           ...       ...       ...       ...       ...       ...       ...   
3163     6.630383  0.962934  0.763182  0.200836  0.131884  0.182790  0.083770   
3164     2.503954  0.960716  0.709570  0.013683  0.116221  0.188980  0.034409   
3165     6.604509  0.946854  0.654196  0.008006  0.142056  0.209918  0.039506   
3166     5.388298  0.950436  0.675470  0.212202  0.143659  0.172375  0.034483   
3167     5.769115  0.938829  0.601529  0.267702  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx  
0     0.275862  0.007812  0.007812  0.007812  0.000000  0.000000  
1     0.250000  0.009014  0.007812  0.054688  0.046875  0.052632  
2     0.271186  0.007990  0.007812  0.015625  0.007812  0.046512  
3     0.250000  0.201497  0.007812  0.562500  0.554688  0.247119  
4     0.266667  0.712812  0.007812  5.484375  5.476562  0.208274  
...        ...       ...       ...       ...       ...       ...  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  

[3168 rows x 20 columns]

In [56]:
Y

0         male
1         male
2         male
3         male
4         male
         ...  
3163    female
3164    female
3165    female
3166    female
3167    female
Name: label, Length: 3168, dtype: object

## Converting string values to int type for labels

In [57]:
from  sklearn.preprocessing import LabelEncoder

In [58]:
le = LabelEncoder()

In [60]:
Y =le.fit_transform(Y)

In [61]:
Y

array([1, 1, 1, ..., 0, 0, 0])

## Data Standardization

In [62]:
#Standardization refers to shifting the distribution of each attribute to have a mean of zero
#and a standard deviation of one (unit variance). It is useful to standardize attributes for a model. 
#Standardization of datasets is a common requirement for many machine learning estimators implemented in scikit-learn;
#they might behave badly if the individual features do not more or less look like standard normally distributed data.

In [63]:
from sklearn.preprocessing import StandardScaler

In [64]:
scaler = StandardScaler()

In [65]:
X = scaler.fit_transform(X)

In [66]:
X

array([[-4.04924806,  0.4273553 , -4.22490077, ..., -1.43142165,
        -1.41913712, -1.45477229],
       [-3.84105325,  0.6116695 , -3.99929342, ..., -1.41810716,
        -1.4058184 , -1.01410294],
       [-3.46306647,  1.60384791, -4.09585052, ..., -1.42920257,
        -1.41691733, -1.06534356],
       ...,
       [-1.29877326,  2.32272355, -0.05197279, ..., -0.5992661 ,
        -0.58671739,  0.17588664],
       [-1.2452018 ,  2.012196  , -0.01772849, ..., -0.41286326,
        -0.40025537,  1.14916112],
       [-0.51474626,  2.14765111, -0.07087873, ..., -1.27608595,
        -1.2637521 ,  1.47567886]])

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.8,random_state=42)

In [69]:
from sklearn.svm import SVC

In [70]:
clf = SVC()

In [71]:
clf.fit(X_train,Y_train)

SVC()

In [73]:
y_pred = clf.predict(X_test)

In [74]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [75]:
accuracy_score(Y_test,y_pred)

0.9755424063116371

In [76]:
precision_score(Y_test,y_pred)

0.9740973312401884

In [77]:
recall_score(Y_test,y_pred)

0.9771653543307086

In [78]:
f1_score(Y_test,y_pred)

0.97562893081761

In [79]:
from sklearn.metrics import confusion_matrix

In [80]:
confusion_matrix(Y_test,y_pred)

array([[1232,   33],
       [  29, 1241]], dtype=int64)

In [89]:
# Kernel=RBF(Radial Basis Function)

clf1 = SVC(kernel='rbf')
clf1.fit(X_train,Y_train)
y_pred1 = clf1.predict(X_test)
print('Accuracy Score:')
print(metrics.accuracy_score(Y_test,y_pred1))

Accuracy Score:
0.9755424063116371


In [90]:
# Kernel = Ploynomial

svc = SVC(kernel='poly')
svc.fit(X_train,Y_train)
y_pred2=svc.predict(X_test)
print('Accuracy Score:')
print(metrics.accuracy_score(Y_test,y_pred2))

Accuracy Score:
0.9451676528599605
